language: cpp
compiler:
  - clang
notifications:
  email: 
      - code@donner.at
julia:
  - release
  - nightly
script:
  - julia -e 'Pkg.init(); Pkg.clone("FunctionalDataUtils")'
  - julia -e 'Pkg.test("FunctionalDataUtils")'

# language: julia
# os:
#   - linux
#   - osx
# julia:
#   - release
#   - nightly
# sudo: false
# notifications:
#   email:
#     - code@donner.at
