language: julia
os:
  - linux
  - osx
notifications:
  email: 
      - code@donner.at
julia:
  - release
  - nightly
script:
  - julia -e 'Pkg.init(); Pkg.clone("FunctionalDataUtils")'
  - julia -e 'Pkg.test("FunctionalDataUtils")'
